title: The 5 Domains of Health Informatics
description:

url: http://kristie625.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: kristie625
   twitter: 
   facebook: 
   email: kristie_625@yahoo.com

google_analytics: ""
